@startwbs
* /ns-3
** /src
***_ Contains internal module
*** /ndnSIM
****_ Simulator module for NDN
*** /network
**** /utils
***** /sgi-hashmap.h
******_ Required for satellite-network/model/gsl-channel.h
*** /satellite
****_ Modified version from originally https://gitlab.inesctec.pt/pmms/ns3-satellite
** /scratch
***_ Default testing scenerios for ns-3
** /contrib
***_ Contains external modules
*** /basic-sim
****_ Basic simulation helper module for TCP https://github.com/snkas/basic-sim/tree/3b32597c183e1039be7f0bede17d36d354696776
*** /satellite-network
****_ Extension of ns3-satellite module
@endwbs